// <auto-generated />
namespace WebAPISuite.Migrations.ClientDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ClientAutoReply : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ClientAutoReply));
        
        string IMigrationMetadata.Id
        {
            get { return "201509242220118_ClientAutoReply"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
